AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: "test1-ui-artifacts-poc-zero-downtime"
        SigningBehavior: "always"  # Use "never", "no-override", or "always"
        OriginAccessControlOriginType: "s3"
        SigningProtocol: "sigv4"  # Use "sigv4" for S3 signed URLs
  MyCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: "MyOrigin"
            DomainName: "ui-artifacts-poc-zero-downtime.s3.eu-west-1.amazonaws.com"  # Replace with your S3 bucket or custom domain
            OriginAccessControlId: "test-ui-artifacts-poc-zero-downtime"  # Attach the OAC
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref MyOriginAccessControl  # You can specify an OAI if using S3 origin

        Enabled: "true"
        DefaultCacheBehavior:
          TargetOriginId: "MyOrigin"
          ViewerProtocolPolicy: "redirect-to-https"  # Can be 'allow-all', 'redirect-to-https', 'https-only'
          AllowedMethods:
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"  # The object to serve by default

