version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - node --version
      - npm --version
      - aws cloudformation package --region eu-west-1 --template-file main.yml --s3-bucket zero-downtime-poc-devops-artifact --output-template-file main.template
      #prepare all [nested file] in main file to deploy on cloudformation 
artifacts:
  files:
    - main.template
    #deploy main temlplate with below file-name
  name: "zero-downtime-poc-infrastructure.zip"